name: Test Hugo Build

on:
  push:
    branches:
    tags:
    paths_ignored:
      - "**.md"
  pull_request:
    paths_ignored:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.1
    steps:
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Test Build with Hugo
        run: |
          cd exampleSite
          hugo --themesDir=../.. --theme=hugo-theme-jane
